'use client'

import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import '@solana/wallet-adapter-react-ui/styles.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import dynamic from 'next/dynamic';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const outfit = Outfit({
  subsets: ['latin'],
  display: 'swap',
})

// Dynamically import the wallet provider with no SSR
const WalletProvider = dynamic(
  () => import('@/components/WalletProvider'),
  {
    ssr: false,
    loading: () => null
  }
);

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased dark`}>
        <WalletProvider>
          <AntdRegistry>
            {children}
          </AntdRegistry>
        </WalletProvider>
      </body>
    </html>
  );
}
